management:
  ## port change
#  server:
#    port: 9292
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true

## env info
info:
  app:
    name: hello-actuator
    company: h3
logging:
  level:
    com.example.actuator.controller: debug
