management:
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
info:
  app:
    name: hello-actuator
    company: h3
